[package]
name = "wafel_core"
version = "0.1.0"
edition = "2018"

[lib]
name = "wafel_core"
crate-type = ["cdylib"]

[dependencies]
derive_more = "0.99.5"
nom = "5.1.1"
object = "0.18.0"
gimli = "0.20.0"
topological-sort = "0.1.0"
textwrap = "0.11.0"
itertools = "0.9.0"
dlopen = "0.1.8"
rand = "0.7.3"
pyo3 = { version = "0.11.1", features = ["extension-module"] }
derivative = "2.1.1"
serde_json = "1.0.55"
lazy_static = "1.4.0"
indexmap = "1.4.0"
serde = { version = "1.0.115", features = ["derive", "rc"] }
lru = "0.6.0"
deepsize = "0.1.2"
winapi = { version = "0.3.9", features = ["dbghelp", "processthreadsapi"] }
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git" }
futures = "0.3.5"
winit = "=0.22.1" # https://github.com/rust-windowing/winit/issues/1698
bytemuck = "1.3.1"
nalgebra = "0.22.0"

[build-dependencies]
walkdir = "2.3.1"

[profile.release]
debug = true
incremental = true
